### ISSUE TITLE
be able to define decrypted output

### ISSUE THREAD

**Issue by matthias-jeutner** [ssh-vault/ssh-vault#17]
When viewing instead of a standard output being able to specifing a special output path

**Comment by nbari** [comment]
@matthias-jeutner  hi, nice catch, please upgrade to version `0.10.0` a new flag has been added, now you can specify an output file, for example:

    cat /path/to/file.pdf.ssh | ssh-vault -o /safe/storage/file.pdf view

Please give a try and let me know if is working from your side.

**Comment by matthias-jeutner** [comment]
@nbari Thanks a lot for fast fixing. Piping is till not working. It does not request the credential of the private key. Without pipe its working nice!

**Comment by nbari** [comment]
@matthias-jeutner for now when using ssh-keys that require to enter a password you will have to specify the file, example:

    ssh-vault -o /safe/storage/file.pdf view /path/to/file.pdf.ssh

This only happens on Linux, FreeBSD, Windows, for Mac os/darwin **piping** is possible only if you allow `ssh-vault` to read the credentials from the keychain, this works on a mac because of to this #12 

Will try to achieve the same behavior on Linux,FreeBSD, meanwhile will keep ticket open for further references.

**Comment by matthias-jeutner** [comment]
thanks a lot. the origin idea behind your project was for sure a different one instead of replacing functionality from gpg, so with that workaround it's totally fine for me.
