### ISSUE TITLE
High Sierra password prompting fail

### ISSUE THREAD

**Issue by tmaher** [ssh-vault/ssh-vault#31]
https://github.com/ssh-vault/ssh-vault/issues/6#issuecomment-365611055

@nbari - sticking this in a new issue for my own visibility. If you'd rather reopen #6 and track it there, it's all the same to me. I'll try to take a look this weekend.

**Comment by nbari** [comment]
Hi @tmaher I was trying in a new MacBook with macOS High Sierra and notice that now there is not anymore the prompt dialog asking to use the keychain and while trying to view a "vault" I need to type the password.

I can ssh to remote hosts without the need to type the password but can't make **ssh-vault** to use the keychain in order to avoid having to type the password.

**Comment by nbari** [comment]
https://github.com/keybase/go-keychain/issues/28

**Comment by nbari** [comment]
added option -p:

     -p, --passphrase <passphrase>  Passphrase of the private ssh key [env: SSH_VAULT_PASSPHRASE=]
