### ISSUE TITLE
unable to use ssh-agent

### ISSUE THREAD

**Issue by briner** [ssh-vault/ssh-vault#54]
Reading the #6, it felt that there was some integration with ssh-vault and ssh-agent. I'am wishing that the decryption made with `ssh-vault view <a_vault>` will occurs without to have to enter the passphrase of my ssh private key.

Is there any chance that it will work ?

Information on my package
```bash
ssh -V
  # OpenSSH_8.7p1 Debian-2, OpenSSL 1.1.1l  24 Aug 2021
./ssh-vault -v
  # 0.12.8
```

**Comment by nbari** [comment]
I really miss that feature, it was just great and easy to decrypt/encrypt but the latest versions of SSH  (macOS) don't allow it anymore, the way it was working is that the password was returned and therefore It could be used to decrypt, but from my understanding was unique to macOS, other distros never return the password, so because of security concerns macOS disabled it. maybe something could be built as a wrapper or safe storage, ideas are welcome being aware that this may not be the safest thing to do but simplify many things like when automating a deployment pipeline and still wanting to have your secrets encrypted in an `ssh-vault` (but being aware that the ssh passphrase will need to be exposed somehow since needs to be used)

maybe an option to call a script before decrypting so that we could call something like:

    ssh-vault -w /path/to/wrapper view file

in where `wrapper` is something like:

```
#!/bin/sh
gpg --quiet --batch --decrypt vault.gpg
```

you need a `gpg` agent first so that it can decrypt the file `vault.gpg` containing your passphrase and then use it for decrypting /encrypting

This, besides supporting ed25519 keys and changing the codebase to `rust` is in the roadmap, ideas are more than welcome.

**Comment by nbari** [comment]
Hi @briner,  please try the latest version, option `-p` should help with this:

     -p, --passphrase <passphrase>  Passphrase of the private ssh key [env: SSH_VAULT_PASSPHRASE=]

For example, you could use `op` from 1password with something like this:

    ssh-vault v -k /path/to/private_key -p $(op item get "ssh-vault test" --fields password) /path/to/vault

in case want to use gpg, here an example: https://github.com/ssh-vault/ssh-vault/blob/main/test_data/vaultpw.sh
