### ISSUE TITLE
Unconventional fingerprint calculation

### ISSUE THREAD

**Issue by nsauk** [ssh-vault/ssh-vault#56]
This is not a bug report, this is a note for any who will try to use this software. And probably a README update request.

I spent about half an hour in trying to figure out what's wrong with my keys, and then realized that you're using some unconventional way to calculate the key fingerprint.

OpenSSH MD5 fingerprint (as it's used in many other software, especially with ssh-* in the name) of [test_data/id_rsa.pub](https://github.com/ssh-vault/ssh-vault/blob/bcf687340bba1fbd9cd00672d965d9b501dae259/test_data/id_rsa.pub) is `95:84:27:28:3c:32:9d:80:39:13:8d:cc:90:3e:4b:e8`:
```bash
wget https://raw.githubusercontent.com/ssh-vault/ssh-vault/bcf687340bba1fbd9cd00672d965d9b501dae259/test_data/id_rsa.pub
ssh-keygen -lf id_rsa.pub -E md5 
4096 MD5:95:84:27:28:3c:32:9d:80:39:13:8d:cc:90:3e:4b:e8 no comment (RSA)
```

And `55:cd:f2:7e:4c:0b:e5:a7:6e:6c:fc:6b:8e:58:9d:15` is a MD5 hash of binary representation of the same key in PKCS8 format (aka SSH2 format):
```bash
ssh-keygen -e -f id_rsa.pub -m pkcs8 | openssl pkey -pubin -outform der | openssl md5 -c
(stdin)= 55:cd:f2:7e:4c:0b:e5:a7:6e:6c:fc:6b:8e:58:9d:15
```

You wrote a few words about this in [this blog post](https://ssh-vault.com/post/fingerprint/), but as I'm not AWS user I had no idea how these formats differ.

**Comment by nbari** [comment]
Hi @nsauk latest version includes both fingerprints apart supporting now ed25519, please give it a try and let me know if works as expected

**Comment by nsauk** [comment]
@nbari as far as I can understand you didn't changed the MD5 hash generation as hashes still differ between `echo | ssh-vault create -k path/to/key` and `ssh-keygen -E md5 -lf path/to/key`. But I'm not sure if it will be a troube for someone since this issue has no likes or comments from users for 1.5 years. Probably you can drop MD5 hashes at all and use SHA256 for any key format.

**Comment by nbari** [comment]
hi @nsauk, thanks for testing,   regarding the fingerprints,  you have now both the standard SHA256 (`ssh-keygen -lf`) and for legacy to preserve older vaults with MD5 (only for RSA, ed25519 returns `SHA2561` matching ssh-keygen output )

I  can't entirely remove the md5 hash, since is used to verify the vault and by doing so will break older "vaults" created with rsa keys, also AWS is still using MD5 (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/verify-keys.html) for imported keys, maybe in some years it can be entirely removed
